/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 17:20:21 UTC 
 * Modify at your own risk.
 */

package com.appspot.android_technician.serverApi.model;

/**
 * Model definition for ComponentCollection.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the serverApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ComponentCollection extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Component> items;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Component> getItems() {
    return items;
  }

  /**
   * @param items items or {@code null} for none
   */
  public ComponentCollection setItems(java.util.List<Component> items) {
    this.items = items;
    return this;
  }

  @Override
  public ComponentCollection set(String fieldName, Object value) {
    return (ComponentCollection) super.set(fieldName, value);
  }

  @Override
  public ComponentCollection clone() {
    return (ComponentCollection) super.clone();
  }

}
