/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-13 at 17:20:21 UTC 
 * Modify at your own risk.
 */

package com.appspot.android_technician.serverApi.model;

/**
 * Model definition for Order.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the serverApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Order extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String addres;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long billId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String city;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime createDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String customer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String customerPhone;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String detailes;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long finish;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fullAddress;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long orderNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long start;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String technicianComments;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long technicianId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String title;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAddres() {
    return addres;
  }

  /**
   * @param addres addres or {@code null} for none
   */
  public Order setAddres(java.lang.String addres) {
    this.addres = addres;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getBillId() {
    return billId;
  }

  /**
   * @param billId billId or {@code null} for none
   */
  public Order setBillId(java.lang.Long billId) {
    this.billId = billId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCity() {
    return city;
  }

  /**
   * @param city city or {@code null} for none
   */
  public Order setCity(java.lang.String city) {
    this.city = city;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getCreateDate() {
    return createDate;
  }

  /**
   * @param createDate createDate or {@code null} for none
   */
  public Order setCreateDate(com.google.api.client.util.DateTime createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCustomer() {
    return customer;
  }

  /**
   * @param customer customer or {@code null} for none
   */
  public Order setCustomer(java.lang.String customer) {
    this.customer = customer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCustomerPhone() {
    return customerPhone;
  }

  /**
   * @param customerPhone customerPhone or {@code null} for none
   */
  public Order setCustomerPhone(java.lang.String customerPhone) {
    this.customerPhone = customerPhone;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDetailes() {
    return detailes;
  }

  /**
   * @param detailes detailes or {@code null} for none
   */
  public Order setDetailes(java.lang.String detailes) {
    this.detailes = detailes;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getFinish() {
    return finish;
  }

  /**
   * @param finish finish or {@code null} for none
   */
  public Order setFinish(java.lang.Long finish) {
    this.finish = finish;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFullAddress() {
    return fullAddress;
  }

  /**
   * @param fullAddress fullAddress or {@code null} for none
   */
  public Order setFullAddress(java.lang.String fullAddress) {
    this.fullAddress = fullAddress;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getOrderNumber() {
    return orderNumber;
  }

  /**
   * @param orderNumber orderNumber or {@code null} for none
   */
  public Order setOrderNumber(java.lang.Long orderNumber) {
    this.orderNumber = orderNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getStart() {
    return start;
  }

  /**
   * @param start start or {@code null} for none
   */
  public Order setStart(java.lang.Long start) {
    this.start = start;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * @param status status or {@code null} for none
   */
  public Order setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTechnicianComments() {
    return technicianComments;
  }

  /**
   * @param technicianComments technicianComments or {@code null} for none
   */
  public Order setTechnicianComments(java.lang.String technicianComments) {
    this.technicianComments = technicianComments;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTechnicianId() {
    return technicianId;
  }

  /**
   * @param technicianId technicianId or {@code null} for none
   */
  public Order setTechnicianId(java.lang.Long technicianId) {
    this.technicianId = technicianId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitle() {
    return title;
  }

  /**
   * @param title title or {@code null} for none
   */
  public Order setTitle(java.lang.String title) {
    this.title = title;
    return this;
  }

  @Override
  public Order set(String fieldName, Object value) {
    return (Order) super.set(fieldName, value);
  }

  @Override
  public Order clone() {
    return (Order) super.clone();
  }

}
